-- Создание базы и staging-таблицы для сырых данных.
CREATE DATABASE IF NOT EXISTS cashback;

CREATE TABLE IF NOT EXISTS cashback.cashback_staging (
    `ключ_клиента` String,
    `регион_проживания` String,
    `город_проживания` String,
    `возраст` String,
    `пол` String,
    `месяц_покупок` String,
    `оборот_аптеки` String,
    `оборот_рестораны` String,
    `оборот_одежда_и_обувь` String,
    `оборот_автоуслуги` String,
    `оборот_супермаркеты` String,
    `оборот_такси` String,
    `оборот_красота` String,
    `оборот_развлечения` String,
    `оборот_жд_билеты` String,
    `оборот_образование` String,
    `оборот_дом_и_ремонт` String,
    `оборот_спорттовары` String,
    `оборот_животные` String,
    `оборот_цветы` String,
    `оборот_фастфуд` String,
    `оборот_каршеринг` String,
    `оборот_аренда_авто` String,
    `активация_кэшбэка_аптеки` String,
    `активация_кэшбэка_рестораны` String,
    `активация_кэшбэка_одежда_и_обувь` String,
    `активация_кэшбэка_автоуслуги` String,
    `активация_кэшбэка_супермаркеты` String,
    `активация_кэшбэка_такси` String,
    `активация_кэшбэка_красота` String,
    `активация_кэшбэка_развлечения` String,
    `активация_кэшбэка_жд_билеты` String,
    `активация_кэшбэка_образование` String,
    `активация_кэшбэка_дом_и_ремонт` String,
    `активация_кэшбэка_спорттовары` String,
    `активация_кэшбэка_животные` String,
    `активация_кэшбэка_цветы` String,
    `активация_кэшбэка_фастфуд` String,
    `активация_кэшбэка_каршеринг` String,
    `активация_кэшбэка_аренда_авто` String,
    `кэшбэк_аптеки` String,
    `кэшбэк_рестораны` String,
    `кэшбэк_одежда_и_обувь` String,
    `кэшбэк_автоуслуги` String,
    `кэшбэк_супермаркеты` String,
    `кэшбэк_такси` String,
    `кэшбэк_красота` String,
    `кэшбэк_развлечения` String,
    `кэшбэк_жд_билеты` String,
    `кэшбэк_образование` String,
    `кэшбэк_дом_и_ремонт` String,
    `кэшбэк_спорттовары` String,
    `кэшбэк_животные` String,
    `кэшбэк_цветы` String,
    `кэшбэк_фастфуд` String,
    `кэшбэк_каршеринг` String,
    `кэшбэк_аренда_авто` String
) ENGINE = MergeTree
ORDER BY tuple();

-- Справочник клиентов.
CREATE TABLE IF NOT EXISTS cashback.dim_clients (
    client_id UInt64,
    region String,
    city String,
    age UInt8,
    gender LowCardinality(String)
) ENGINE = MergeTree
ORDER BY client_id;

-- Справочник месяцев.
CREATE TABLE IF NOT EXISTS cashback.dim_months (
    month Date
) ENGINE = MergeTree
ORDER BY month;

-- Фактовая таблица: обороты + активации + начисленный кэшбэк.
CREATE TABLE IF NOT EXISTS cashback.fact_cashback (
    client_id UInt64,
    month Date,
    turnover_apteki Float64,
    turnover_restaurants Float64,
    turnover_clothes Float64,
    turnover_auto Float64,
    turnover_supermarkets Float64,
    turnover_taxi Float64,
    turnover_beauty Float64,
    turnover_entertainment Float64,
    turnover_rail Float64,
    turnover_education Float64,
    turnover_home Float64,
    turnover_sport Float64,
    turnover_pets Float64,
    turnover_flowers Float64,
    turnover_fastfood Float64,
    turnover_carsharing Float64,
    turnover_rent Float64,
    activated_apteki Nullable(UInt8),
    activated_restaurants Nullable(UInt8),
    activated_clothes Nullable(UInt8),
    activated_auto Nullable(UInt8),
    activated_supermarkets Nullable(UInt8),
    activated_taxi Nullable(UInt8),
    activated_beauty Nullable(UInt8),
    activated_entertainment Nullable(UInt8),
    activated_rail Nullable(UInt8),
    activated_education Nullable(UInt8),
    activated_home Nullable(UInt8),
    activated_sport Nullable(UInt8),
    activated_pets Nullable(UInt8),
    activated_flowers Nullable(UInt8),
    activated_fastfood Nullable(UInt8),
    activated_carsharing Nullable(UInt8),
    activated_rent Nullable(UInt8),
    cashback_apteki Float64,
    cashback_restaurants Float64,
    cashback_clothes Float64,
    cashback_auto Float64,
    cashback_supermarkets Float64,
    cashback_taxi Float64,
    cashback_beauty Float64,
    cashback_entertainment Float64,
    cashback_rail Float64,
    cashback_education Float64,
    cashback_home Float64,
    cashback_sport Float64,
    cashback_pets Float64,
    cashback_flowers Float64,
    cashback_fastfood Float64,
    cashback_carsharing Float64,
    cashback_rent Float64
) ENGINE = MergeTree
ORDER BY (month, client_id);
