-- ClickHouse: аналитическая витрина.
CREATE DATABASE IF NOT EXISTS cashback;

CREATE TABLE IF NOT EXISTS cashback.fact_cashback (
    client_id UInt64,
    month Date,
    turnover_apteki Float64,
    turnover_restaurants Float64,
    turnover_clothes Float64,
    turnover_auto Float64,
    turnover_supermarkets Float64,
    turnover_taxi Float64,
    turnover_beauty Float64,
    turnover_entertainment Float64,
    turnover_rail Float64,
    turnover_education Float64,
    turnover_home Float64,
    turnover_sport Float64,
    turnover_pets Float64,
    turnover_flowers Float64,
    turnover_fastfood Float64,
    turnover_carsharing Float64,
    turnover_rent Float64,
    activated_apteki Nullable(UInt8),
    activated_restaurants Nullable(UInt8),
    activated_clothes Nullable(UInt8),
    activated_auto Nullable(UInt8),
    activated_supermarkets Nullable(UInt8),
    activated_taxi Nullable(UInt8),
    activated_beauty Nullable(UInt8),
    activated_entertainment Nullable(UInt8),
    activated_rail Nullable(UInt8),
    activated_education Nullable(UInt8),
    activated_home Nullable(UInt8),
    activated_sport Nullable(UInt8),
    activated_pets Nullable(UInt8),
    activated_flowers Nullable(UInt8),
    activated_fastfood Nullable(UInt8),
    activated_carsharing Nullable(UInt8),
    activated_rent Nullable(UInt8),
    cashback_apteki Float64,
    cashback_restaurants Float64,
    cashback_clothes Float64,
    cashback_auto Float64,
    cashback_supermarkets Float64,
    cashback_taxi Float64,
    cashback_beauty Float64,
    cashback_entertainment Float64,
    cashback_rail Float64,
    cashback_education Float64,
    cashback_home Float64,
    cashback_sport Float64,
    cashback_pets Float64,
    cashback_flowers Float64,
    cashback_fastfood Float64,
    cashback_carsharing Float64,
    cashback_rent Float64
) ENGINE = MergeTree
ORDER BY (month, client_id);
