-- PostgreSQL: основная БД для данных о клиентах и покупках.

CREATE SCHEMA IF NOT EXISTS cashback;

CREATE TABLE IF NOT EXISTS cashback.cashback_staging (
    ключ_клиента TEXT,
    регион_проживания TEXT,
    город_проживания TEXT,
    возраст TEXT,
    пол TEXT,
    месяц_покупок TEXT,
    оборот_аптеки TEXT,
    оборот_рестораны TEXT,
    оборот_одежда_и_обувь TEXT,
    оборот_автоуслуги TEXT,
    оборот_супермаркеты TEXT,
    оборот_такси TEXT,
    оборот_красота TEXT,
    оборот_развлечения TEXT,
    оборот_жд_билеты TEXT,
    оборот_образование TEXT,
    оборот_дом_и_ремонт TEXT,
    оборот_спорттовары TEXT,
    оборот_животные TEXT,
    оборот_цветы TEXT,
    оборот_фастфуд TEXT,
    оборот_каршеринг TEXT,
    оборот_аренда_авто TEXT,
    активация_кэшбэка_аптеки TEXT,
    активация_кэшбэка_рестораны TEXT,
    активация_кэшбэка_одежда_и_обувь TEXT,
    активация_кэшбэка_автоуслуги TEXT,
    активация_кэшбэка_супермаркеты TEXT,
    активация_кэшбэка_такси TEXT,
    активация_кэшбэка_красота TEXT,
    активация_кэшбэка_развлечения TEXT,
    активация_кэшбэка_жд_билеты TEXT,
    активация_кэшбэка_образование TEXT,
    активация_кэшбэка_дом_и_ремонт TEXT,
    активация_кэшбэка_спорттовары TEXT,
    активация_кэшбэка_животные TEXT,
    активация_кэшбэка_цветы TEXT,
    активация_кэшбэка_фастфуд TEXT,
    активация_кэшбэка_каршеринг TEXT,
    активация_кэшбэка_аренда_авто TEXT,
    кэшбэк_аптеки TEXT,
    кэшбэк_рестораны TEXT,
    кэшбэк_одежда_и_обувь TEXT,
    кэшбэк_автоуслуги TEXT,
    кэшбэк_супермаркеты TEXT,
    кэшбэк_такси TEXT,
    кэшбэк_красота TEXT,
    кэшбэк_развлечения TEXT,
    кэшбэк_жд_билеты TEXT,
    кэшбэк_образование TEXT,
    кэшбэк_дом_и_ремонт TEXT,
    кэшбэк_спорттовары TEXT,
    кэшбэк_животные TEXT,
    кэшбэк_цветы TEXT,
    кэшбэк_фастфуд TEXT,
    кэшбэк_каршеринг TEXT,
    кэшбэк_аренда_авто TEXT
);

CREATE TABLE IF NOT EXISTS cashback.dim_clients (
    client_id BIGINT PRIMARY KEY,
    region TEXT,
    city TEXT,
    age SMALLINT,
    gender TEXT
);

CREATE TABLE IF NOT EXISTS cashback.dim_months (
    month DATE PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS cashback.fact_cashback (
    client_id BIGINT REFERENCES cashback.dim_clients(client_id),
    month DATE REFERENCES cashback.dim_months(month),
    turnover_apteki DOUBLE PRECISION,
    turnover_restaurants DOUBLE PRECISION,
    turnover_clothes DOUBLE PRECISION,
    turnover_auto DOUBLE PRECISION,
    turnover_supermarkets DOUBLE PRECISION,
    turnover_taxi DOUBLE PRECISION,
    turnover_beauty DOUBLE PRECISION,
    turnover_entertainment DOUBLE PRECISION,
    turnover_rail DOUBLE PRECISION,
    turnover_education DOUBLE PRECISION,
    turnover_home DOUBLE PRECISION,
    turnover_sport DOUBLE PRECISION,
    turnover_pets DOUBLE PRECISION,
    turnover_flowers DOUBLE PRECISION,
    turnover_fastfood DOUBLE PRECISION,
    turnover_carsharing DOUBLE PRECISION,
    turnover_rent DOUBLE PRECISION,
    activated_apteki SMALLINT,
    activated_restaurants SMALLINT,
    activated_clothes SMALLINT,
    activated_auto SMALLINT,
    activated_supermarkets SMALLINT,
    activated_taxi SMALLINT,
    activated_beauty SMALLINT,
    activated_entertainment SMALLINT,
    activated_rail SMALLINT,
    activated_education SMALLINT,
    activated_home SMALLINT,
    activated_sport SMALLINT,
    activated_pets SMALLINT,
    activated_flowers SMALLINT,
    activated_fastfood SMALLINT,
    activated_carsharing SMALLINT,
    activated_rent SMALLINT,
    cashback_apteki DOUBLE PRECISION,
    cashback_restaurants DOUBLE PRECISION,
    cashback_clothes DOUBLE PRECISION,
    cashback_auto DOUBLE PRECISION,
    cashback_supermarkets DOUBLE PRECISION,
    cashback_taxi DOUBLE PRECISION,
    cashback_beauty DOUBLE PRECISION,
    cashback_entertainment DOUBLE PRECISION,
    cashback_rail DOUBLE PRECISION,
    cashback_education DOUBLE PRECISION,
    cashback_home DOUBLE PRECISION,
    cashback_sport DOUBLE PRECISION,
    cashback_pets DOUBLE PRECISION,
    cashback_flowers DOUBLE PRECISION,
    cashback_fastfood DOUBLE PRECISION,
    cashback_carsharing DOUBLE PRECISION,
    cashback_rent DOUBLE PRECISION,
    PRIMARY KEY (client_id, month)
);

-- Нормализованный факт по категориям (long format).
CREATE TABLE IF NOT EXISTS cashback.fact_cashback_category (
    client_id BIGINT REFERENCES cashback.dim_clients(client_id),
    month DATE REFERENCES cashback.dim_months(month),
    category TEXT,
    turnover DOUBLE PRECISION,
    cashback DOUBLE PRECISION,
    activation_state TEXT,
    PRIMARY KEY (client_id, month, category)
);

-- Витрина клиент-месяц с агрегатами и QC-метриками.
CREATE TABLE IF NOT EXISTS cashback.mart_client_month (
    client_id BIGINT,
    month DATE,
    total_turnover DOUBLE PRECISION,
    total_cashback DOUBLE PRECISION,
    eligible_cnt SMALLINT,
    chosen_cnt SMALLINT,
    has_subscription_guess BOOLEAN,
    PRIMARY KEY (client_id, month)
);

